SysFacturacionLibreria.UI.AppWebAspCore/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SysFacturacionLibreria.EntidadesDeNegocio;
using SysFacturacionLibreria.LogicaDeNegocio;

namespace SysFacturacionLibreria.UI.AppWebAspCore.Controllers
{
    public class ClienteController : Controller
    {
        ClienteBL ClienteBL = new ClienteBL();
        // GET: ClienteController
        public async Task<IActionResult> Index(Cliente pCliente = null)
        {
            if (pCliente == null)
                pCliente = new Cliente();
            if (pCliente.Top_Aux == 0)
                pCliente.Top_Aux = 10;
            else if (pCliente.Top_Aux == -1)
                pCliente.Top_Aux = 0;
            var Cliente = await ClienteBL.BuscarAsync(pCliente);
            ViewBag.Top = pCliente.Top_Aux;
            return View(Cliente);
        }

        // GET: ClienteController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var rol = await ClienteBL.ObtenerPorIdAsync(new Cliente { IdCliente = id });
            return View(rol);
        }

        // GET: CategoriaController/Create
        public IActionResult Create()
        {
            ViewBag.Error = "";
            return View();
        }


        // POST: ClienteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Cliente pCliente)
        {
            try
            {
                int result = await ClienteBL.CrearAsync(pCliente);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pCliente);
            }
        }

        // GET: ClienteController/Edit/5
        public async Task<IActionResult> Edit(Cliente pCliente)
        {
            var Cliente = await ClienteBL.ObtenerPorIdAsync(pCliente);
            ViewBag.Error = "";
            return View(Cliente);
        }

        // POST: ClienteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Cliente pCliente)
        {
            try
            {
                int result = await ClienteBL.ModificarAsync(pCliente);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pCliente);
            }
        }

        // GET: ClienteController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            ViewBag.Error = "";
            var cliente = await ClienteBL.ObtenerPorIdAsync(new Cliente { IdCliente = id });
            return View(cliente);
        }

        // POST: ClienteController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var cliente = await ClienteBL.ObtenerPorIdAsync(new Cliente { IdCliente = id });
                int result = await ClienteBL.EliminarAsync(cliente);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View();
            }
        }
    }
}

SysFacturacionLibreria.UI.AppWebAspCore/Controllers/FacturaController.cs
using Microsoft.AspNetCore.Mvc;
using SysFacturacionLibreria.LogicaDeNegocio;
using SysFacturacionLibreria.EntidadesDeNegocio;
using System;
using System.Threading.Tasks;

namespace SysFacturacionLibreria.UI.AppWebAspCore.Controllers
{
    public class FacturaController : Controller
    {
        private readonly FacturaBL facturaBL;

        public FacturaController()
        {
            facturaBL = new FacturaBL();
        }

        // GET: Factura
        public async Task<IActionResult> Index(Factura pFactura = null)
        {
            if (pFactura == null)
                pFactura = new Factura();
            if (pFactura.Top_Aux == 0)
                pFactura.Top_Aux = 10;
            else if (pFactura.Top_Aux == -1)
                pFactura.Top_Aux = 0;
            var Factura = await facturaBL.BuscarAsync(pFactura);
            ViewBag.Top = pFactura.Top_Aux;
            return View(Factura);
        }

        // GET: Factura/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var factura = await facturaBL.ObtenerPorIdAsync(new Factura { IdFactura = id });
            return View(factura);
        }

        // GET: Factura/Create
        public IActionResult Create()
        {
            ViewBag.Error = "";
            return View();
        }

        // POST: Factura/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Factura pFactura)
        {
            try
            {
                int result = await facturaBL.CrearAsync(pFactura);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pFactura);
            }
        }

        // GET: Factura/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var factura = await facturaBL.ObtenerPorIdAsync(new Factura { IdFactura = id });
            ViewBag.Error = "";
            return View(factura);
        }

        // POST: Factura/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Factura pFactura)
        {
            try
            {
                int result = await facturaBL.ModificarAsync(pFactura);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pFactura);
            }
        }

        // GET: Factura/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            ViewBag.Error = "";
            var factura = await facturaBL.ObtenerPorIdAsync(new Factura { IdFactura = id });
            return View(factura);
        }

        // POST: Factura/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            try
            {
                await facturaBL.EliminarAsync(new Factura { IdFactura = id });
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(new Factura { IdFactura = id });
            }
        }
    }
}

SysFacturacionLibreria.UI.AppWebAspCore/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SysFacturacionLibreria.EntidadesDeNegocio;
using SysFacturacionLibreria.LogicaDeNegocio;

namespace SysFacturacionLibreria.UI.AppWebAspCore.Controllers
{
    public class ProductoController : Controller
    {
        ProductoBL ProductoBL = new ProductoBL();
        // GET: ProductoController
        public async Task<IActionResult> Index(Producto pProducto = null)
        {
            if (pProducto == null)
                pProducto = new Producto();
            if (pProducto.Top_Aux == 0)
                pProducto.Top_Aux = 10;
            else if (pProducto.Top_Aux == -1)
                pProducto.Top_Aux = 0;
            var Producto = await ProductoBL.BuscarAsync(pProducto);
            ViewBag.Top = pProducto.Top_Aux;
            return View(Producto);
        }

        // GET: CategoriaController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var rol = await ProductoBL.ObtenerPorIdAsync(new Producto { IdProducto = id });
            return View(rol);
        }

        // GET: ProductoController/Create
        public IActionResult Create()
        {
            ViewBag.Error = "";
            return View();
        }

        // POST: ProductoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Producto pProducto)
        {
            try
            {
                int result = await ProductoBL.CrearAsync(pProducto);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pProducto);
            }
        }

        // GET: ProductoContProductoler/Edit/5
        public async Task<IActionResult> Edit(Producto pProducto)
        {
            var Producto = await ProductoBL.ObtenerPorIdAsync(pProducto);
            ViewBag.Error = "";
            return View(Producto);
        }

        // POST: ProductoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Producto pProducto)
        {
            try
            {
                int result = await ProductoBL.ModificarAsync(pProducto);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pProducto);
            }
        }

        // GET: ProductoController/Delete/5
        public async Task<IActionResult> Delete(Producto pProducto)
        {
            ViewBag.Error = "";
            var Producto = await ProductoBL.ObtenerPorIdAsync(pProducto);
            return View(Producto);
        }

        // POST: ProductoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, Producto pProducto)
        {
            try
            {
                int result = await ProductoBL.EliminarAsync(pProducto);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pProducto);
            }
        }
    }
}

SysFacturacionLibreria.UI.AppWebAspCore/Controllers/RolController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;


// Agregar la siguiente librerias
using SysFacturacionLibreria.EntidadesDeNegocio;
using SysFacturacionLibreria.LogicaDeNegocio;
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;



namespace SysFacturacionLibreria.UI.AppWebAspCore.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    //controllerRols
    public class RolController : Controller

    {
        RolBL rolBL = new RolBL();
        // GET: RolController1
        public async Task<IActionResult> Index(Rol pRol = null)
        {
            if (pRol == null)
                pRol = new Rol();
            if (pRol.Top_Aux == 0)
                pRol.Top_Aux = 10;
            else if (pRol.Top_Aux == -1)
                pRol.Top_Aux = 0;
            var roles = await rolBL.BuscarAsync(pRol);
            ViewBag.Top = pRol.Top_Aux;
            return View(roles);
        }


        // GET: RolController1/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var rol = await rolBL.ObtenerPorIdAsync(new Rol { Id = id });
            return View(rol);
        }

        // GET: RolController1/Create
        public IActionResult Create()
        {
            ViewBag.Error = "";
            return View();
        }

        // POST: RolController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Rol pRol)
        {
            try
            {
                int result = await rolBL.CrearAsync(pRol);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pRol);
            }

        }
        // GET: RolController1/Edit/5
        public async Task<IActionResult> Edit(Rol pRol)
        {
            var rol = await rolBL.ObtenerPorIdAsync(pRol);
            ViewBag.Error = "";
            return View(rol);
        }

        // POST: RolController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Rol pRol)
        {
            try
            {
                int result = await rolBL.ModificarAsync(pRol);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pRol);
            }
        }

        // GET: RolController1/Delete/5
        public async Task<IActionResult> Delete(Rol pRol)
        {
            ViewBag.Error = "";
            var rol = await rolBL.ObtenerPorIdAsync(pRol);
            return View(rol);
        }

        // POST: RolController1/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, Rol pRol)
        {
            try
            {
                int result = await rolBL.EliminarAsync(pRol);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pRol);
            }
        }
    }
}
//Terminado1234

SysFacturacionLibreria.UI.AppWebAspCore/Views/Shared/_Layout.cshtml
@*@*<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FacturacionLibreria</title>
   <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="styles.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
   
</head>
<body>
   <header>
        <style>
            .navbar {
                flex-direction: column;
                align-items: flex-start;
            }

            .navbar-collapse {
                margin-top: 10px;
            }

            .nav-item {
                margin-bottom: 5px;
            }
        </style>
       

        @if (User.Identity.IsAuthenticated)
                {

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FacturacionLibreria</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
               
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="s nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Rol" asp-action="Index">Rol</a>
                            </li>
                            <li class="nav-item">
                                <a class="fas fa-user nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index"> Usuario</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="CambiarPassword">Cambiar password</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Cliente</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="Index">Producto</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="Index">Categoria</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Proveedor" asp-action="Index">Proveedor</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Factura" asp-action="Index">Factura</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="DetalleDeVenta" asp-action="Index">Venta</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="CerrarSesion">Cerrar sesión</a>
                            </li>
                        </ul>
                    </div>
               
            </div>
        </nav>
        }
    </header>




    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Seguridad Web
        </div>
    </footer>*@
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>*@

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FacturacionLibreria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="styles.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href=~/css/Menu.css />
    <link rel="stylesheet" href="~/js/Menu.js" />

   

</head>
<body>
    <header>
        @if (User.Identity.IsAuthenticated)
        {
     

            <div class=''>
                <div class="dashboard-nav">
                    <header>
                        <a href="#!" class="menu-toggle"><i class="fas fa-bars"></i></a><a href="#"
                                                                                       class="brand-logo">
                            <i class="fas fa-anchor"></i> <span>MENU</span>
                        </a>
                    </header>
                    <nav class="dashboard-nav-list">
                        <div class='dashboard-nav-dropdown'>
                            <li class="nav-item">
                                <a class="dashboard-nav-item" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i> Inicio</a>
                            </li>
                        </div>
                        <div class='dashboard-nav-dropdown'>
                            <li class="nav-item">
                                <a class="dashboard-nav-item" asp-area="" asp-controller="Rol" asp-action="Index"><i class="fas fa-user-tag"></i> Rol</a>
                            </li>
                          </div>
                          <div class='dashboard-nav-dropdown'>
                            <li class="nav-item">
                                <a class="dashboard-nav-item" asp-area="" asp-controller="Usuario" asp-action="Index"><i class="fas fa-user"></i> Usuario</a>
                            </li>
                        </div>
                        <div class='dashboard-nav-dropdown'>
                            <li class="nav-item">
                                <a class="dashboard-nav-item" asp-area="" asp-controller="Usuario" asp-action="CambiarPassword"><i class="fas fa-key"></i> Cambiar password</a>
                            </li>
                        </div>
                        <div class='dashboard-nav-dropdown'>
                            <li class="nav-item">
                                <a class="dashboard-nav-item" asp-area="" asp-controller="Cliente" asp-action="Index"><i class="fas fa-users"></i> Cliente</a>
                            </li>
                        </div>
                        <div class='dashboard-nav-dropdown'>
                            <li class="nav-item">
                                <a class="dashboard-nav-item" asp-area="" asp-controller="Producto" asp-action="Index"><i class="fas fa-book"></i> Producto</a>
                            </li>
                        </div>
                        <div class='dashboard-nav-dropdown'>
                            <li class="nav-item">
                                <a class="dashboard-nav-item" asp-area="" asp-controller="Categoria" asp-action="Index"><i class="fas fa-folder-open"></i> Categoria</a>
                            </li>
                        </div>
                        <div class='dashboard-nav-dropdown'>
                            <li class="nav-item">
                                <a class="dashboard-nav-item" asp-area="" asp-controller="Proveedor" asp-action="Index"><i class="fas fa-truck"></i> Proveedor</a>
                            </li>
                        </div>
                        @*en esta parte esta el submenu de m*@
                        <div class='dashboard-nav-dropdown'>
                            <li class="nav-item">
                                <a class="dashboard-nav-item" asp-area="" asp-controller="Factura" asp-action="Index"><i class="fas fa-file-invoice"></i> Factura</a>
                            </li>
                        </div>
                        <li class="nav-item">
                            <a class="dashboard-nav-item" asp-area="" asp-controller="DetalleDeVenta" asp-action="Index"><i class="fas fa-shopping-cart"></i> Venta</a>
                        </li>
                       @* <a href="#" class="dashboard-nav-item"><i class="fas fa-cogs"></i> Settings </a><a href="#" class="dashboard-nav-item"><i class="fas fa-user"></i> Profile </a>*@
                        <div class="nav-item-divider"></div>
                       
                        <li class="nav-item">
                            <a class="" asp-area="" asp-controller="Usuario" asp-action="CerrarSesion"><i class="fas fa-sign-out-alt"></i> Cerrar sesión</a>
                        </li>
                    </nav>
                </div>
                
            </div>
        }
    </header>

 
    <div class='dashboard-app'>
   @* <header class='dashboard-toolbar'><a href="#!" class="menu-toggle"><i class="fas fa-bars"></i></a></header>*@
    <div class='dashboard-content'>
          <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
            
        </div>
    </div>
</div>
   
</body>
</html>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $(function () {
            $("form input[name]").trigger("blur");
        });
    </script>
}